{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ubichill.fullname" . }}-backend
  labels:
    {{- include "ubichill.labels" . | nindent 4 }}
    component: backend
  {{- with .Values.service.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ubichill.selectorLabels" . | nindent 4 }}
    component: backend
{{- end }}