{{- if .Values.backend.enabled }}
{{- if .Values.backend.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ubichill.fullname" . }}-backend-secrets
  labels:
    {{- include "ubichill.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secretEnv }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
{{- end }}
