{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ubichill.serviceAccountName.backend" . }}
  labels:
    {{- include "ubichill.labels" . | nindent 4 }}
    component: backend
automountServiceAccountToken: true
---
{{- end }}
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ubichill.serviceAccountName.frontend" . }}
  labels:
    {{- include "ubichill.labels" . | nindent 4 }}
    component: frontend
automountServiceAccountToken: false
{{- end }}